version: '3.8'

services:
  techdb:
    image: postgres
    container_name: techdb
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql
    
  pgadmintechin:
    image: dpage/pgadmin4
    container_name: pgadmintechin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DB_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DB_EMAIL_PASSWORD}
    ports:
      - "5050:80"